baseURL = 'https://lyywyz123456789.github.io/lwww/'
languageCode = 'en-us'
title = '一只小学霸'
theme = 'ananke'
publishDir = "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup. goldmark]
[markup. goldmark. renderer]
unsafe = true
canonifyurls = true